stages:
  - build
  - tests
  - deploy

variables:
  FLASK_ENV: 'production'  # Default environment variable

# Job to build and tests the application
build_and_test:
  stage: build
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest tests/
  artifacts:
    paths:
      - tests/report.xml
    reports:
      junit: tests/report.xml
  tags:
    - practice-1

# Job to deploy to development environment
dev:
  stage: deploy
  image: google/cloud-sdk:alpine
  before_script:
    - echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/gcloud-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
    - gcloud config set project your-project-id
  script:
    - echo "Deploying to development environment..."
    - gcloud app deploy --quiet --version dev
  environment:
    name: development
    url: https://dev.example.com  # URL for the dev environment
  only:
    - develop
  tags:
    - practice-1

# Job to deploy to testing environment
test:
  stage: deploy
  image: google/cloud-sdk:alpine
  before_script:
    - echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/gcloud-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
    - gcloud config set project your-project-id
  script:
    - echo "Deploying to testing environment..."
    - gcloud app deploy --quiet --version tests
  environment:
    name: testing
    url: https://test.example.com  # URL for the tests environment
  only:
    - merge_requests
  tags:
    - practice-1

# Job to deploy to production environment
prod:
  stage: deploy
  image: google/cloud-sdk:alpine
  before_script:
    - echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/gcloud-key.json
    - gcloud auth activate-service-account --key-file /tmp/gcloud-key.json
    - gcloud config set project your-project-id
  script:
    - echo "Deploying to production environment..."
    - gcloud app deploy --quiet --version prod
  environment:
    name: production
    url: https://www.example.com  # URL for the production environment
  only:
    - main
  tags:
    - practice-1
