stages:
  - build
  - test
  - deploy

variables:
  FLASK_ENV: 'production'  # Default environment variable

build_and_test:
  stage: build
  script:
    - 'C:\Users\ashwa\AppData\Local\Programs\Python\Python312\python.exe -m pip install -r requirements.txt'
    - 'C:\Users\ashwa\AppData\Local\Programs\Python\Python312\python.exe -m pytest tests/'
  artifacts:
    paths:
      - tests/report.xml
    reports:
      junit: tests/report.xml
  tags:
    - practice-1

deploy_to_dev:
  stage: deploy
  script:
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd auth activate-service-account --key-file C:\Path\To\gcloud-key.json'
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd config set project your-project-id'
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd app deploy --quiet --version dev'
  environment:
    name: development
    url: https://dev.example.com  # URL for the dev environment
  only:
    - develop
  tags:
    - practice-1

deploy_to_test:
  stage: deploy
  script:
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd auth activate-service-account --key-file C:\Path\To\gcloud-key.json'
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd config set project your-project-id'
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd app deploy --quiet --version test'
  environment:
    name: testing
    url: https://test.example.com  # URL for the test environment
  only:
    - merge_requests
  tags:
    - practice-1

deploy_to_prod:
  stage: deploy
  script:
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd auth activate-service-account --key-file C:\Path\To\gcloud-key.json'
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd config set project your-project-id'
    - 'C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd app deploy --quiet --version prod'
  environment:
    name: production
    url: https://www.example.com  # URL for the production environment
  only:
    - main
  tags:
    - practice-1
