stages:
  - build
  - test
  - deploy

variables:
  PROJECT_ID: regal-scholar-423322
  REGION: us-central1
  REPO: gitlab-app

build_image:
  stage: build
  script:
    - 'C:\Users\ashwa\AppData\Local\Programs\Python\Python312\python.exe -m pip install -r requirements.txt'
    - docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:${CI_COMMIT_REF_SLUG} .
    - echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://${REGION}-docker.pkg.dev
    - docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:${CI_COMMIT_REF_SLUG}
  artifacts:
    paths:
      - tests/report.xml
    reports:
      junit: tests/report.xml
  tags:
    - practice-1

deploy_to_dev:
  stage: deploy
  script:
    - echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://${REGION}-docker.pkg.dev
    - docker pull ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:${CI_COMMIT_REF_SLUG}
    - docker tag ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:${CI_COMMIT_REF_SLUG} ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:dev
    - docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:dev
  environment:
    name: development
    url: https://dev.example.com  # URL for the dev environment
  only:
    - develop
  tags:
    - practice-1

deploy_to_test:
  stage: deploy
  script:
    - echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://${REGION}-docker.pkg.dev
    - docker pull ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:${CI_COMMIT_REF_SLUG}
    - docker tag ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:${CI_COMMIT_REF_SLUG} ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:test
    - docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:test
  environment:
    name: testing
    url: https://test.example.com  # URL for the test environment
  only:
    - merge_requests
  tags:
    - practice-1

deploy_to_prod:
  stage: deploy
  script:
    - echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://${REGION}-docker.pkg.dev
    - docker pull ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:${CI_COMMIT_REF_SLUG}
    - docker tag ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:${CI_COMMIT_REF_SLUG} ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:prod
    - docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO}/chatapp:prod
  environment:
    name: production
    url: https://www.example.com  # URL for the production environment
  only:
    - main
  tags:
    - practice-1
