stages:
  - build
  - test
  - deploy

variables:
  PROJECT_ID: regal-scholar-423322
  REGION: us-central1
  REPO: gitlab-app
  IMAGE_TAG: ${CI_COMMIT_REF_SLUG}  # Use branch name or commit SHA as the image tag
  DOCKER_REGISTRY: ${REGION}-docker.pkg.dev
  IMAGE_NAME: ${DOCKER_REGISTRY}/${PROJECT_ID}/${REPO}/chatapp
  GOOGLE_APPLICATION_CREDENTIALS_FILE: "gcloud-key.json"  # Path to write the key file

before_script:
  # Print the first 10 characters of GOOGLE_APPLICATION_CREDENTIALS to debug
  - powershell -Command "Write-Output ($env:GOOGLE_APPLICATION_CREDENTIALS.Substring(0, [Math]::Min($env:GOOGLE_APPLICATION_CREDENTIALS.Length, 100)))"

  # Write the JSON key file from the GitLab CI/CD variable
  - powershell -Command "Set-Content -Path '${GOOGLE_APPLICATION_CREDENTIALS_FILE}' -Value '$env:GOOGLE_APPLICATION_CREDENTIALS'"

  # Debugging step: Check if the file is created and has content
  - powershell -Command "Test-Path '${GOOGLE_APPLICATION_CREDENTIALS_FILE}'"
  - powershell -Command "Get-Content '${GOOGLE_APPLICATION_CREDENTIALS_FILE}' | Select-Object -First 10"

  # Authenticate Google Cloud SDK using the written JSON key file
  - powershell -Command "gcloud auth activate-service-account --key-file='${GOOGLE_APPLICATION_CREDENTIALS_FILE}'"
  - gcloud config set project ${PROJECT_ID}

  # Configure Docker to use Google Cloud Docker registry
  - gcloud auth configure-docker ${DOCKER_REGISTRY}

build_image:
  stage: build
  script:
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
  tags:
    - practice-1

test:
  stage: test
  script:
    - python -m pip install -r requirements.txt
    - pytest
  tags:
    - practice-1

deploy_to_dev:
  stage: deploy
  script:
    - docker pull ${IMAGE_NAME}:${IMAGE_TAG}
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:dev
    - docker push ${IMAGE_NAME}:dev
  environment:
    name: development
    url: https://dev.example.com
  only:
    - develop
  tags:
    - practice-1

deploy_to_test:
  stage: deploy
  script:
    - docker pull ${IMAGE_NAME}:${IMAGE_TAG}
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:test
    - docker push ${IMAGE_NAME}:test
  environment:
    name: testing
    url: https://test.example.com
  only:
    - merge_requests
  tags:
    - practice-1

deploy_to_prod:
  stage: deploy
  script:
    - docker pull ${IMAGE_NAME}:${IMAGE_TAG}
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:prod
    - docker push ${IMAGE_NAME}:prod
  environment:
    name: production
    url: https://www.example.com
  only:
    - main
  tags:
    - practice-1
