runtime: python39  # Use the Python 3.9 runtime
entrypoint: gunicorn -b :$PORT main:app  # Command to run your application

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  SECRET_KEY: ${GOOGLE_APPLICATION_CREDENTIALS}  # Replace with your actual secret key
  DATABASE_URL: 'postgresql://postgres:Ashu123@34.72.51.3/postgres'  # Replace with your actual database URL
  # Add any other environment variables your application requires

# Optional: Instance class and automatic scaling settings
instance_class: F2  # Choose an instance class, F2 is a reasonable starting point

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
