runtime: python39  # Use the Python 3.9 runtime
entrypoint: gunicorn -b :$PORT app:app  # Command to run your application

handlers:
  - url: /static
    static_dir: app/static  # Point to your static directory

  - url: /.*
    script: auto

#env_variables:
##   Path to your key file
##  KEY_FILE_PATH: '/tmp/gcp-key.json'
##   Remove DATABASE_URL if not used
##   DATABASE_URL: 'postgresql://postgres:Ashu123@34.72.51.3/postgres'

# Optional: Instance class and automatic scaling settings
instance_class: F2  # Choose an instance class, F2 is a reasonable starting point

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 4
